%% Generated by the Erlang ASN.1 compiler. Version: 5.0.18
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CoinProto.

-ifndef(_COINPROTO_HRL_).
-define(_COINPROTO_HRL_, true).

-record('BranchSet_SEQOF', {
  slot,
  branch
  %% with extension mark
}).

-record('Branch', {
  'latest-hash',
  'current-difficulty',
  'cumulative-difficulty',
  length,
  coinbase,
  supply
  %% with extension mark
}).

-record('Block', {
  version,
  index,
  hash = asn1_NOVALUE,
  'prev-hash',
  timestamp,
  transactions = asn1_NOVALUE,
  nonce,
  difficulty
  %% with extension mark
}).

-record('Transaction', {
  hash,
  in,
  out
  %% with extension mark
}).

-record('TransactionIn', {
  'out-hash' = asn1_NOVALUE,
  'out-index',
  signature = asn1_NOVALUE
  %% with extension mark
}).

-record('TransactionOut', {
  address,
  amount
  %% with extension mark
}).

-endif. %% _COINPROTO_HRL_
